class_name MacroTrainingTelemetrySchema
extends RefCounted

const SCHEMA_VERSION := "macro_training_v2"
const LEGACY_V1_COLUMN_COUNT := 23

const STEP_COLUMNS: Array[String] = [
	"telemetry_schema_version",
	"episode_id",
	"macro_step_index",
	"seed",
	"step_index",
	"player_id",
	"actor_player_id",
	"round_number",
	"active_player_id",
	"policy_name",
	"scenario_name",
	"rules_version",
	"action_space_layout_key",
	"phase",
	"victory_points",
	"resources_json",
	"city_count",
	"road_count",
	"breach_count",
	"total_demons",
	"game_finished",
	"winner_id",
	"legal_action_ids_json",
	"legal_mask_json",
	"selected_action_id",
	"selected_action_kind",
	"action_params_json",
	"pre_observation_json",
	"post_observation_json",
	"reward",
	"reward_components_json",
	"terminal",
	"event_summaries",
	"structured_events_json",
	"draft_age",
	"infection_rate",
	"development_hand_json",
	"draft_pack_size",
	"waiting_for_draft",
]
